title: CEEO Innovations 
email: your-email@tuftsceeo.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl:  # the subpath of your site, e.g. /blog
url: "http://ceeoinnovations.github.io"
twitter_username: tuftsceeo
github_username:  tuftsceeoinnovations
my_categories:
  - SPIKE Prime
  - 3D Printing
  - EV3/NXT
  - Robotics
  - Makerspaces
  - LabVIEW



# Build settings
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
  authors:
    output: true
  fullproducts:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
